### ISSUE TITLE
Feature Set

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-Explorer#1]
- [x] Current Target
- [x] Current Hashrate
- [x] Total Siacoins
- [x] Current Blockchain Size
- [x] Transaction Volume
- [x] Size of Each block.

**Comment by triazo** [comment]
Can you clarify the size of each block? For example, are you looking for a long list of blocks, with associated sizes?

**Comment by DavidVorick** [comment]
basically. Or perhaps a graph of sorts.

**Comment by DavidVorick** [comment]
After thinking about this more:
1. 'Siacoins sent' is not a useful metric
2. Hashrate @ 10 blocks is not a useful metric (instead of 10,30,100,100, just do 25,100, 1000)

After that, I think the most useful thing to have is a way to view blocks of a certain height, view the transactions inside of the blocks, view the inputs and outputs of the transaction, and to be able to follow addresses around and get histories on them (see the source and destination). But we'll worry about that after the baseline stuff is in place.
