### ISSUE TITLE
Startup Time + Rescan

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-Explorer#11]
I remember you wanted a rescan function for  the explorer. I'm not sure why it would be necessary, you should assume that rescan is something that would take many minutes, and when the blockchain gets much larger, it may take many hours.

Furthermore, you mentioned that the block explorer currently takes around 7 minutes to start up. 7 minutes isn't too bad, but it's a lot to deal with if you are trying to debug something or probe a specific error. It's a much bigger problem when our blockchain changes from 8000 blocks with a few transactions per block to 50000 blocks with 100+ transactions per block. A 700 minute startup time isn't going to cut it.

**Comment by triazo** [comment]
I don't remember mentioning a rescan, although I can see how it may be useful in some situations. Ideally, we won't rebuild the database on startup, I think this can be done by simply not adding a block to the database if it is already there.

**Comment by triazo** [comment]
Merged into Siad
